<div class="container">
    <div class="jumbotron">
        <h1>My First Bootstrap Page</h1>
        <p>Resize this responsive page to see the effect!</p>
    </div>
    <form class="form-horizontal">
        <fieldset>

            <!-- Form Name -->
            <legend>Fale Conosco</legend>

            <!-- Text input-->
            <div class="control-group">
                <label class="control-label" for="nome">Nome:</label>
                <div class="controls">
                    <input id="nome" name="nome" placeholder="Digite seu nome!" class="input-xlarge" type="text">
                    <p class="help-block">nome</p>
                </div>
            </div>

            <!-- Text input-->
            <div class="control-group">
                <label class="control-label" for="email">E-mail:</label>
                <div class="controls">
                    <input id="email" name="email" placeholder="Digite seu e-mail!" class="input-xlarge" type="text">
                    <p class="help-block">help</p>
                </div>
            </div>

            <!-- Textarea -->
            <div class="control-group">
                <label class="control-label" for="mensagem">Mensagem</label>
                <div class="controls">                     
                    <textarea id="mensagem" name="mensagem">Digite sua mensagem!</textarea>
                </div>
            </div>

            <!-- Button -->
            <div class="control-group">
                <label class="control-label" for="enviar"></label>
                <div class="controls">
                    <button id="enviar" name="enviar" class="btn btn-primary">Enviar</button>
                </div>
            </div>

        </fieldset>
    </form>

</div>
</div>
